### ISSUE TITLE
Fresh install not working

### ISSUE THREAD

**Issue by studnitz** [storybooks/vue-cli-plugin-storybook#14]
Hello,

I tried to run either the `serve:storybook` and the `build:storybook` scripts, but they both fail on a freshly created vue cli project with a standard template (babel + eslint).

My specs: 
OS: Windows 10
```
$ node -v
v10.1.0
$ npm -v
5.6.0
$ yarn -v
1.9.4
```
And this is the error log:

```
$ yarn serve:storybook
yarn run v1.9.4
(node:11448) ExperimentalWarning: The fs.promises API is experimental
$ vue-cli-service serve:storybook -p 6006 -c config/storybook
info @storybook/vue v4.0.0-alpha.16
info
info => Loading custom addons config.
info => Using default webpack setup.
  0% compiling  0% compiling ERROR  TypeError: Cannot read property 'tap' of undefined
TypeError: Cannot read property 'tap' of undefined
    at compiler.hooks.compilation.tap.compilation (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\@vue\preload-webpack-plugin\src\index.js:114:65)
    at SyncHook.eval [as call] (eval at create (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:25:1)
    at SyncHook.lazyCompileHook [as _call] (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.newCompilation (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Compiler.js:504:26)
    at hooks.beforeCompile.callAsync.err (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Compiler.js:540:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\tapable\lib\Hook.js:35:21)
    at Compiler.compile (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Compiler.js:535:28)
    at compiler.hooks.watchRun.callAsync.err (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\tapable\lib\Hook.js:35:21)
    at Watching._go (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Watching.js:40:32)
    at Watching.compiler.readRecords.err (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Watching.js:32:9)
    at Compiler.readRecords (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Compiler.js:402:11)
    at new Watching (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Watching.js:29:17)
    at Compiler.watch (C:\Users\Sputn\Documents\Sources\storybook-test\node_modules\webpack\lib\Compiler.js:201:10)
error Command failed with exit code 1.
```

**Comment by sneko** [comment]
@pksunkara same for me

Note: Storybook team released the v4.0.0-alpha.17+18 that uses Babel 7, will that involve some changes?

**Comment by maikeldaloo** [comment]
Same here, on OSX.
On node.js v9.4.0 as well as v10.8.0. Project started with vue-cli 3.0.0.

**Comment by brennj** [comment]
Can confim this for me too, seems to be directly an issue with `0.4.4`, when I changed it in my `package.json` to `0.4.3`, all works fine.

**Comment by axwalker** [comment]
I still get this error when I pin to `0.4.3`.

**Comment by sneko** [comment]
@axwalker did you remove nodes_modules?

**Comment by axwalker** [comment]
@sneko Yep, removed node_modules. It's using `@storybook/vue v4.0.0-alpha.16`.

**Comment by gabemule** [comment]
Same here, on MacOS 10.13.4

**Comment by kidzki** [comment]
Hello, i got a similar issue after your fix.

Versions
`
$ node -v
v10.9.0
$ npm -v
6.4.0
$ yarn -v
1.9.4
`
Error
`
yarn run v1.9.4
$ vue-cli-service serve:storybook -p 6006 -c config/storybook
info @storybook/vue v4.0.0-alpha.20
info
info => Loading custom addons config.
info => Loading custom webpack config (extending mode).
  0% compiling ERROR  TypeError: Cannot read property 'tap' of undefined
TypeError: Cannot read property 'tap' of undefined
    at compiler.hooks.compilation.tap.compilation (projectfolder/node_modules/@vue/cli-service/lib/webpack/CorsPlugin.js:25:57)
    at SyncHook.eval [as call] (eval at create (projectfolder/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:25:1)
    at SyncHook.lazyCompileHook [as _call] (projectfolder/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.newCompilation (projectfolder/node_modules/webpack/lib/Compiler.js:504:26)
    at hooks.beforeCompile.callAsync.err (projectfolder/node_modules/webpack/lib/Compiler.js:540:29)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (projectfolder/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (projectfolder/node_modules/tapable/lib/Hook.js:35:21)
    at Compiler.compile (projectfolder/node_modules/webpack/lib/Compiler.js:535:28)
    at compiler.hooks.watchRun.callAsync.err (projectfolder/node_modules/webpack/lib/Watching.js:77:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (projectfolder/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (projectfolder/node_modules/tapable/lib/Hook.js:35:21)
    at Watching._go (projectfolder/node_modules/webpack/lib/Watching.js:40:32)
    at Watching.compiler.readRecords.err (projectfolder/node_modules/webpack/lib/Watching.js:32:9)
    at Compiler.readRecords (projectfolder/node_modules/webpack/lib/Compiler.js:402:11)
    at new Watching (projectfolder/node_modules/webpack/lib/Watching.js:29:17)
    at Compiler.watch (projectfolder/node_modules/webpack/lib/Compiler.js:201:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

custom webpack.config
`
const path = require('path')

module.exports = {
  resolve: {
    alias: {
      '~': path.resolve(__dirname, '..', '..', 'src')
    }
  },
  module: {
    rules: [
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader"],
        include: path.resolve(__dirname, '..')
      },
    ]
  }
};

`

**Comment by pksunkara** [comment]
@kidzki What's your vue.config.js? It looks like you have enabled cors, right?

**Comment by kidzki** [comment]
Yes! I set a crossorigin. It woks after i removed the setting from my vue.config

**Comment by kidzki** [comment]
But we both agree that this is a "bug" and needs to be fixed right?

**Comment by pksunkara** [comment]
Yup. https://github.com/storybooks/vue-cli-plugin-storybook/pull/17#issuecomment-418089026
